import { z } from 'zod'

const optStr = z.string().max(2000).optional()
const optStrShort = z.string().max(200).optional()
const optBool = z.boolean().optional()
const optNum = z.preprocess(
  (v) => (typeof v === 'number' && isNaN(v) ? undefined : v),
  z.number().nullable().optional()
)
const optStrArr = z.array(z.string().max(100)).max(40).optional()

export const MenopauseFormSchema = z.object({
  step1: z.object({
    dateFormulaire: z.string().max(20),
    prenom: z.string().min(1).max(100),
    nom: z.string().min(1).max(100),
    dateNaissance: z.string().max(20),
    adresse: z.string().max(500),
    telephone: z.string().max(30),
    email: z.string().email().max(200),
    niss: optStrShort,
    profession: z.string().max(200),
    mutuelle: optStrShort,
    medecinTraitant: optStrShort,
    situationFamiliale: z.string().max(50),
    situationFamilialeAutre: optStrShort,
    preferenceContact: optStrArr,
    langue: z.string().max(10).optional(),
    motifPrincipal: z.string().max(100),
    attentes: optStr,
    souhaitThs: optStr,
    souhaitNonHormonal: optStr,
  }).optional(),

  step2: z.object({
    bilanIntegratif: optStrShort,
    bilanDejaFait: optStrShort,
    bilanGynecologue: optStrShort,
    bilanGeneraliste: optStrShort,
    bilanNutritionniste: optStrShort,
    supplementee: optStrShort,
    supplHormones: optStrShort,
    supplHormonesDetail: optStr,
    supplPlantes: optStrShort,
    supplPlantesDetail: optStr,
    supplComplements: optStrShort,
    supplComplementsDetail: optStr,
    reponseTraitements: optStr,
    famAntecedents: optStrArr,
    famCancerDetail: optStr,
    famInflammatoiresDetail: optStr,
    famAutres: optStr,
    persMaladiesChroniques: optStr,
    persAntecedents: optStrArr,
    persCancerDetail: optStr,
    persCardioDetail: optStr,
    persInflammatoiresDetail: optStr,
    allergies: optStr,
    vaccinations: optStr,
  }).optional(),

  step3: z.object({
    chirurgies: optStr,
    autresAntecedents: optStr,
    mammographieDate: optStrShort,
    mammographieResultat: optStr,
    frottisDate: optStrShort,
    frottisResultat: optStr,
    bilanHormonal: optStr,
    autresExamens: optStr,
    symptomes: optStrArr,
    symptomesAutre: optStr,
    agePremieresRegles: optNum,
    reglesPresentes: optStrShort,
    modifFrequenceCycles: optStrShort,
    modifFrequenceDepuis: optStrShort,
    modifDureeCycles: optStrShort,
    modifDureeJours: optStrShort,
    flux: optStrShort,
    couleur: optStrShort,
    douleursRegles: optStrShort,
    intensiteDouleur: optNum,
    localisationDouleur: optStr,
    contraceptionType: optStr,
    contraceptionMarque: optStrShort,
    contraceptionEffets: optStr,
    traitementEnCours: optStr,
    autresGyneco: optStr,
  }).optional(),

  step4: z.object({
    nombreGrossesses: optNum,
    detailGrossesses: optStr,
    allaitement: optStrShort,
    complicationsObstetricales: optStr,
    sexuellementActive: optStrShort,
    libido: optStrShort,
    frequenceRapports: optStrShort,
    dyspareunie: optStrShort,
    saignementsPostCoitaux: optStrShort,
    troublesDigestifsPelviens: optStr,
    spmMarque: optStrShort,
    cystites: optStrShort,
    vaginites: optStrShort,
    secheresseVaginale: optStrShort,
    taille: optNum,
    poids: optNum,
    variationPonderale: optStrShort,
    sommeilHeures: optNum,
    qualiteSommeil: optStrShort,
    ronflementsSAOS: optStrShort,
    fuitesUrinaires: optStrShort,
    activitePhysiqueType: optStrShort,
    activitePhysiqueFrequence: optStrShort,
  }).optional(),

  step5: z.object({
    tabac: optStrShort,
    dateArretTabac: optStrShort,
    nbCigarettes: optNum,
    alcool: optNum,
    cafes: optNum,
    boissonsEnergisantes: optNum,
    drogues: optStrShort,
    droguesDetail: optStr,
    expositions: optStrArr,
    expositionsAutre: optStrShort,
    nbRepas: optNum,
    regulariteRepas: optStrShort,
    petitDejeuner: optStrShort,
    grignotages: optStrShort,
    jeuneIntermittent: optStrShort,
    sucreSale: optStrShort,
    profilAlimentaire: optStrArr,
    marchePas: optStrShort,
    heuresAssis: optNum,
    hydratation: optNum,
    typeEau: optStrShort,
    nbSelles: optNum,
    regulariteSelles: optStrShort,
    ballonnements: optStrShort,
    acidite: optStrShort,
    bristolScale: optNum,
  }).optional(),

  step6: z.object({
    ressenti: optStr,
    emotions: optStrArr,
    emotionsAutre: optStrShort,
    motivation: optNum,
    anxiete: optNum,
    facteurs: optStr,
    soutienActuel: optStr,
    ressources: optStrArr,
    ressourcesAutre: optStrShort,
    impactQuotidien: optStrArr,
    impactQuotidienAutre: optStrShort,
    priseDePoidsAbdo: optStrShort,
    douleurFoie: optStrShort,
    regulationPoidsDifficile: optStrShort,
    signalAlerte: optStrShort,
    souhaitParlerConsultation: optStrShort,
  }).optional(),

  step7: z.object({
    besoinsAccompagnement: optStrArr,
    besoinsAccompagnementAutre: optStrShort,
    documentsApporter: optStrArr,
    documentsApporterAutre: optStrShort,
  }).optional(),

  step8: z.object({
    consentPolitique: z.literal(true, { errorMap: () => ({ message: 'Consentement obligatoire' }) }),
    consentStatistiques: optBool,
    consentContact: z.literal(true, { errorMap: () => ({ message: 'Consentement obligatoire' }) }),
    partageHonae: z.string().max(200).optional().catch(undefined),
    signature: z.string().min(3).max(200),
    dateSignature: z.string().max(30),
  }).optional(),
})

export type ValidatedMenopauseData = z.infer<typeof MenopauseFormSchema>
