import { z } from 'zod'

const optStr = z.string().max(2000).optional()
const optStrShort = z.string().max(200).optional()
const optBool = z.boolean().optional()
const optNum = z.preprocess(
  (v) => (typeof v === 'number' && isNaN(v) ? undefined : v),
  z.number().nullable().optional()
)
const optStrArr = z.array(z.string().max(100)).max(20).optional()
const ouiNon = z.enum(['oui', 'non']).optional()

export const FormDataSchema = z.object({
  showStep5: z.boolean().optional(),

  step1: z.object({
    dateFormulaire: z.string().max(20),
    completePar: z.string().max(50),
    prenom: z.string().min(1).max(100),
    nom: z.string().min(1).max(100),
    dateNaissance: z.string().max(20),
    adresse: z.string().max(500),
    telephone: z.string().max(30),
    email: z.string().email().max(200),
    niss: optStrShort,
    profession: optStrShort,
    mutuelle: optStrShort,
    medecinTraitant: optStrShort,
    situationFamiliale: z.string().max(50),
    completeParAutre: optStrShort,
    situationFamilialeAutre: optStrShort,
    partenaireSexe: optStrShort,
    partenaireSexeAutre: optStrShort,
    partenairePrenom: optStrShort,
    partenaireNom: optStrShort,
    partenaireAge: optStrShort,
    partenaireProfession: optStrShort,
    preferenceContact: optStrArr,
    langue: z.string().max(10).optional(),
  }).optional(),

  step2: z.object({
    motifPrincipal: optStrShort,
    motifAutre: optStr,
    attentes: optStr,
    bilanFertilite: optStrShort,
    souhaitPreservation: optStrShort,
    conservationOvocytaire: optStrShort,
    conservationSperme: optStrShort,
    essaisNaturels: optStrShort,
    dureeEssais: optStrShort,
    rapportsCibles: optStrShort,
    outilsUtilises: optStrArr,
    parcoursPMAFait: optStrShort,
    parcoursPMA: optStr,
    maladiesChroniques: optStr,
    sopk: ouiNon, endometriose: ouiNon, adenomyose: ouiNon,
    fibromes: ouiNon, infectionsPelviennes: ouiNon,
    autrePathologie: optStr,
    pathologiesEndocriniennes: optStr,
    insuffisanceOvarienne: ouiNon, troublesSurrenaliens: ouiNon,
    diabete: ouiNon, pathologiesHypophysaires: ouiNon,
    allergies: optStr,
    traitementsEnCours: optStr,
    vaccinations: optStrArr,
    thrombose: ouiNon,
  }).optional(),

  step3: z.object({
    agePremieresRegles: optNum,
    regularite: optStrShort,
    dureeRegles: optNum,
    flux: optStrShort,
    douleursRegles: ouiNon,
    intensiteDouleur: optNum,
    localisationDouleur: optStr,
    phaseLuteale: optNum,
    spotting: ouiNon,
    quandSpotting: optStr,
    signesOvulation: optStrArr,
    douleurRapports: optStrShort,
    saignementsPostCoitaux: ouiNon,
    troublesDigestifs: optStr,
    typeContraception: optStrArr,
    marqueContraception: optStrShort,
    dateArretContraception: optStrShort,
    effetsSecondairesContraception: optStr,
    acne: ouiNon, pilosite: ouiNon, chuteCheveux: ouiNon,
    chirurgies: optStr,
    antecedentsFamiliaux: optStrArr,
    antecedentsFamiliauxDetails: optStr,
    serologies: optStrArr,
  }).optional(),

  step4: z.object({
    examensRealises: optStrArr,
    examensRealisesAutre: optStrShort,
    malformationsUterines: optStr,
    nombreGrossesses: optNum,
    detailGrossesses: optStr,
    allaitement: ouiNon,
    dureeAllaitement: optStrShort,
    nombreFaussesCouches: optNum,
    ageGestFC: optStrShort,
    analysesFC: optStr,
    complicationsObstetricales: optStr,
  }).optional(),

  step5: z.object({
    antecedentsMasculins: optStrArr,
    chirurgiesMasculins: optStr,
    traitementsMasculins: optStr,
    fonctionSexuelle: optStrArr,
    frequenceRapports: optNum,
    lubrifiant: ouiNon,
    quelLubrifiant: optStrShort,
    expositions: optStrArr,
    fertilitéAnterieure: ouiNon,
    delaisConception: optStr,
    spermogramme: optStr,
    fragmentationADN: optStr,
    echoGenitourinaire: optStr,
    caryotype: optStr,
    autresExamensMasculins: optStr,
    dernierFrottisDate: optStrShort,
    dernierFrottisResultat: optStr,
    chutCheveux: ouiNon,
  }).optional(),

  step6: z.object({
    stress: optNum,
    evenementsMajeurs: optStr,
    activitePhysique: optStr,
    taille: optNum,
    poids: optNum,
    variationPonderale: optStrShort,
    sommeilHeures: optNum,
    qualiteSommeil: optStrShort,
    ronflementsOAS: optStrArr,
    tabac: optStrShort,
    dateArretTabac: optStrShort,
    nbCigarettes: optNum,
    alcool: optNum,
    cafeine: optNum,
    drogues: optStrShort,
    expositionsProfessionnelles: optStrArr,
    soutienPsychologique: optStrShort,
    nbRepas: optNum,
    profilAlimentaire: optStrArr,
    hydratation: optNum,
    typeEau: optStrShort,
    nbSelles: optNum,
    ballonnements: optStr,
    bristolScale: optNum,
  }).optional(),

  step7: z.object({
    ressentiParcours: optStr,
    emotions: optStrArr,
    motivation: optNum,
    anxiete: optNum,
    facteurs: optStr,
    soutienActuel: optStr,
    ressources: optStrArr,
    impactQuotidien: optStrArr,
    signalAlerte: ouiNon,
    souhaitParlerConsultation: ouiNon,
    besoinsAccompagnement: optStrArr,
    documentsApporter: optStrArr,
  }).optional(),

  step8: z.object({
    consentPolitique: z.literal(true, { errorMap: () => ({ message: 'Consentement obligatoire' }) }),
    consentStatistiques: optBool,
    consentContact: z.literal(true, { errorMap: () => ({ message: 'Consentement obligatoire' }) }),
    partageHonae: z.string().max(200).optional().catch(undefined),
    partagePartenaire: z.string().max(200).optional().catch(undefined),
    signature: z.string().min(3).max(200),
    dateSignature: z.string().max(30),
  }).optional(),
})

export type ValidatedFormData = z.infer<typeof FormDataSchema>
